### ISSUE TITLE
QuizViewController遷移時のエラー問題

### ISSUE THREAD

**Issue by burakon** [ochicchi/4taku#5]
`QuizViewController`に遷移する際下記エラーが表示される。

```
[MC] Lazy loading NSBundle MobileCoreServices.framework
[MC] Loaded MobileCoreServices.framework
```

`UITextView`の `inset` が決まってない状態で `StoryBoard` から作成を始めるから(多分そのあたりの理由)なのか、上記のエラーが出る。
システムエラーなので無視していいし、挙動としてはおかしくないんですが、なんかちょっと気持ち悪い気がする。

### 解決方法
- 1.`UILabel` にする
    - 文字制限が発生する(改行はできる)
- 2.システムエラーなので気にしないでくださいと伝える 
    - システムエラーかどうかの区別がつかない初心者の方にそう伝えるのは不親切かも
- 3.システムエラーを表示させない方法をとる
    - https://qiita.com/mono0926/items/5a8771ef43faf5d9bbcb
    - 初心者におまじないを強制するのは本質的じゃないので避けたい

解決方法としては1 or 2かなと思ってます。どっちにしますか？

**Comment by burakon** [comment]
@ochicchi 1 にする場合自分が作業します！ and スライド修正もします！

**Comment by ochicchi** [comment]
コードマージしました。
